#!/usr/bin/env bash

# Jogos e programas
#alias dontstarvetogether='steam steam://rungameid/322330 & exit'
alias transmission-cli='transmission-remote-cli -c Andrikin:hp1lovecraft@localhost:9091'

# Commandos Gerais
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias free='free -h'
alias grep='grep --color=auto'
alias ls='ls -1N --color=auto --group-directories-first'
alias py='python3'
alias bcp='cpg -g'
alias bmv='mvg -g'
alias reboot='sudo reboot'
alias off='sudo poweroff'
