#!/usr/bin/env bash

# Nnn file manager
nnncd(){
	nnn "$@"

	if [[ -f $NNN_TMPFILE ]];then
		. "$NNN_TMPFILE"
		rm -f "$NNN_TMPFILE" > /dev/null
	fi
	clear
}

# Lf file manager
lfcd(){
   tmp="$(mktemp)"
   lf -last-dir-path="$tmp" "$@"
   if [ -f "$tmp" ]; then
       dir="$(grep --color=never . "$tmp")"
       rm -f "$tmp"
       if [ -d "$dir" ]; then
           if [ "$dir" != "$(pwd)" ]; then
               cd "$dir"
           fi
       fi
   fi
   clear
}

# Fff file manager
ffcd(){
   fff "$@"
   endereco="$(grep --color=never . "${XDG_CACHE_HOME:=${HOME}/.cache}/fff/.fff_d")"
   if [[ $endereco != $(pwd) ]];then
       cd "$endereco"
   fi
   clear
}

extrair_arquivo(){
	if [[ -f $1 ]]; then
		case "$1" in
			*.tar.bz2)   tar xvjf "$1"     ;;
			*.tar.gz)    tar xvzf "$1"     ;;
			*.bz2)       bunzip2 "$1"      ;;
			*.rar)       unrar x "$1"      ;;
			*.gz)        gunzip "$1"       ;;
			*.tar)       tar xvf "$1"      ;;
			*.tbz2)      tar xvjf "$1"     ;;
			*.tgz)       tar xvzf "$1"     ;;
			*.zip)       unzip "$1"        ;;
			*.Z)         uncompress "$1"   ;;
			*.7z)        7z x "$1"         ;;
			*)           echo "Não pode ser extraído!";;
		esac
	else
		echo "$1 Não é um arquivo válido!"
	fi
}
