#!/usr/bin/env bash

# Opções built-in do Bash
shopt -s histappend
shopt -s no_empty_cmd_completion
shopt -s cmdhist

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
	# Rust cargo
	. "$HOME/.cargo/env"
	# Git prompt
	. "$HOME/.git-prompt.sh"
	if [ -f /usr/share/bash-completion/bash_completion ]; then
		. /usr/share/bash-completion/bash_completion
		. /home/andre/.config/bashenv/gh_completion
	elif [ -f /etc/bash_completion ]; then
		. /etc/bash_completion
		. /home/andre/.config/bashenv/gh_completion
	fi
fi

